version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: DockerfileBackEnd
    volumes:
      - ~/.credentials/credentials.json:/root/.credentials/credentials.json
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - OPENAI_API_KEY
      - SERPER_API_KEY
      - GOOGLE_APPLICATION_CREDENTIALS
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: DockerfileFrontEnd
    ports:
      - "3000:3000"